// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("Forside")]
	public partial class Forside {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_buttonFeedback;
		
		private MonoTouch.UIKit.UITextView __mt_labelDescription;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonFeedback")]
		private MonoTouch.UIKit.UIButton buttonFeedback {
			get {
				this.__mt_buttonFeedback = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonFeedback")));
				return this.__mt_buttonFeedback;
			}
			set {
				this.__mt_buttonFeedback = value;
				this.SetNativeField("buttonFeedback", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelDescription")]
		private MonoTouch.UIKit.UITextView labelDescription {
			get {
				this.__mt_labelDescription = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("labelDescription")));
				return this.__mt_labelDescription;
			}
			set {
				this.__mt_labelDescription = value;
				this.SetNativeField("labelDescription", value);
			}
		}
	}
}
