// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("FieldImagePickerScreen")]
	public partial class FieldImagePickerScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIImageView __mt_imageView;
		
		private MonoTouch.UIKit.UIToolbar __mt_toolbar;
		
		private MonoTouch.UIKit.UIActivityIndicatorView __mt_loadView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageView")]
		private MonoTouch.UIKit.UIImageView imageView {
			get {
				this.__mt_imageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageView")));
				return this.__mt_imageView;
			}
			set {
				this.__mt_imageView = value;
				this.SetNativeField("imageView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("toolbar")]
		private MonoTouch.UIKit.UIToolbar toolbar {
			get {
				this.__mt_toolbar = ((MonoTouch.UIKit.UIToolbar)(this.GetNativeField("toolbar")));
				return this.__mt_toolbar;
			}
			set {
				this.__mt_toolbar = value;
				this.SetNativeField("toolbar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("loadView")]
		private MonoTouch.UIKit.UIActivityIndicatorView loadView {
			get {
				this.__mt_loadView = ((MonoTouch.UIKit.UIActivityIndicatorView)(this.GetNativeField("loadView")));
				return this.__mt_loadView;
			}
			set {
				this.__mt_loadView = value;
				this.SetNativeField("loadView", value);
			}
		}
	}
}
