// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("FieldDatePickerScreen")]
	public partial class FieldDatePickerScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIDatePicker __mt_datePicker;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("datePicker")]
		private MonoTouch.UIKit.UIDatePicker datePicker {
			get {
				this.__mt_datePicker = ((MonoTouch.UIKit.UIDatePicker)(this.GetNativeField("datePicker")));
				return this.__mt_datePicker;
			}
			set {
				this.__mt_datePicker = value;
				this.SetNativeField("datePicker", value);
			}
		}
	}
}
