// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("FieldLocationScreen")]
	public partial class FieldLocationScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.MapKit.MKMapView __mt_mapView;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btnGps;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btnClear;
		
		private MonoTouch.UIKit.UILabel __mt_txtLocation;
		
		private MonoTouch.UIKit.UISegmentedControl __mt_mapTypeControl;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mapView")]
		private MonoTouch.MapKit.MKMapView mapView {
			get {
				this.__mt_mapView = ((MonoTouch.MapKit.MKMapView)(this.GetNativeField("mapView")));
				return this.__mt_mapView;
			}
			set {
				this.__mt_mapView = value;
				this.SetNativeField("mapView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnGps")]
		private MonoTouch.UIKit.UIBarButtonItem btnGps {
			get {
				this.__mt_btnGps = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btnGps")));
				return this.__mt_btnGps;
			}
			set {
				this.__mt_btnGps = value;
				this.SetNativeField("btnGps", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnClear")]
		private MonoTouch.UIKit.UIBarButtonItem btnClear {
			get {
				this.__mt_btnClear = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btnClear")));
				return this.__mt_btnClear;
			}
			set {
				this.__mt_btnClear = value;
				this.SetNativeField("btnClear", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtLocation")]
		private MonoTouch.UIKit.UILabel txtLocation {
			get {
				this.__mt_txtLocation = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("txtLocation")));
				return this.__mt_txtLocation;
			}
			set {
				this.__mt_txtLocation = value;
				this.SetNativeField("txtLocation", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mapTypeControl")]
		private MonoTouch.UIKit.UISegmentedControl mapTypeControl {
			get {
				this.__mt_mapTypeControl = ((MonoTouch.UIKit.UISegmentedControl)(this.GetNativeField("mapTypeControl")));
				return this.__mt_mapTypeControl;
			}
			set {
				this.__mt_mapTypeControl = value;
				this.SetNativeField("mapTypeControl", value);
			}
		}
	}
}
