// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("HeaderStatsFilter")]
	public partial class HeaderStatsFilter {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_labelFilter;
		
		private MonoTouch.UIKit.UISegmentedControl __mt_segmentedControl;
		
		private MonoTouch.UIKit.UIButton __mt_buttonFilter;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelFilter")]
		private MonoTouch.UIKit.UILabel labelFilter {
			get {
				this.__mt_labelFilter = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelFilter")));
				return this.__mt_labelFilter;
			}
			set {
				this.__mt_labelFilter = value;
				this.SetNativeField("labelFilter", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("segmentedControl")]
		private MonoTouch.UIKit.UISegmentedControl segmentedControl {
			get {
				this.__mt_segmentedControl = ((MonoTouch.UIKit.UISegmentedControl)(this.GetNativeField("segmentedControl")));
				return this.__mt_segmentedControl;
			}
			set {
				this.__mt_segmentedControl = value;
				this.SetNativeField("segmentedControl", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonFilter")]
		private MonoTouch.UIKit.UIButton buttonFilter {
			get {
				this.__mt_buttonFilter = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonFilter")));
				return this.__mt_buttonFilter;
			}
			set {
				this.__mt_buttonFilter = value;
				this.SetNativeField("buttonFilter", value);
			}
		}
	}
}
