// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("HeaderJaktItem")]
	public partial class HeaderJaktItem {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_labelSted;
		
		private MonoTouch.UIKit.UILabel __mt_labelDato;
		
		private MonoTouch.UIKit.UIButton __mt_buttonImage;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelSted")]
		private MonoTouch.UIKit.UILabel labelSted {
			get {
				this.__mt_labelSted = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelSted")));
				return this.__mt_labelSted;
			}
			set {
				this.__mt_labelSted = value;
				this.SetNativeField("labelSted", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelDato")]
		private MonoTouch.UIKit.UILabel labelDato {
			get {
				this.__mt_labelDato = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelDato")));
				return this.__mt_labelDato;
			}
			set {
				this.__mt_labelDato = value;
				this.SetNativeField("labelDato", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonImage")]
		private MonoTouch.UIKit.UIButton buttonImage {
			get {
				this.__mt_buttonImage = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonImage")));
				return this.__mt_buttonImage;
			}
			set {
				this.__mt_buttonImage = value;
				this.SetNativeField("buttonImage", value);
			}
		}
	}
}
