// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("HeaderJeger")]
	public partial class HeaderJeger {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_labelName;
		
		private MonoTouch.UIKit.UIButton __mt_buttonImage;
		
		private MonoTouch.UIKit.UILabel __mt_labelNotes;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelName")]
		private MonoTouch.UIKit.UILabel labelName {
			get {
				this.__mt_labelName = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelName")));
				return this.__mt_labelName;
			}
			set {
				this.__mt_labelName = value;
				this.SetNativeField("labelName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonImage")]
		private MonoTouch.UIKit.UIButton buttonImage {
			get {
				this.__mt_buttonImage = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonImage")));
				return this.__mt_buttonImage;
			}
			set {
				this.__mt_buttonImage = value;
				this.SetNativeField("buttonImage", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelNotes")]
		private MonoTouch.UIKit.UILabel labelNotes {
			get {
				this.__mt_labelNotes = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelNotes")));
				return this.__mt_labelNotes;
			}
			set {
				this.__mt_labelNotes = value;
				this.SetNativeField("labelNotes", value);
			}
		}
	}
}
