// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("HeaderLoggItem")]
	public partial class HeaderLoggItem {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_buttonImage;
		
		private MonoTouch.UIKit.UIImageView __mt_imgArt;
		
		private MonoTouch.UIKit.UIImageView __mt_imgJeger;
		
		private MonoTouch.UIKit.UIImageView __mt_imgPosisjon;
		
		private MonoTouch.UIKit.UIImageView __mt_imgSkudd;
		
		private MonoTouch.UIKit.UIImageView __mt_imgNotater;
		
		private MonoTouch.UIKit.UIImageView __mt_imgBilde;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonImage")]
		private MonoTouch.UIKit.UIButton buttonImage {
			get {
				this.__mt_buttonImage = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonImage")));
				return this.__mt_buttonImage;
			}
			set {
				this.__mt_buttonImage = value;
				this.SetNativeField("buttonImage", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgArt")]
		private MonoTouch.UIKit.UIImageView imgArt {
			get {
				this.__mt_imgArt = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgArt")));
				return this.__mt_imgArt;
			}
			set {
				this.__mt_imgArt = value;
				this.SetNativeField("imgArt", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgJeger")]
		private MonoTouch.UIKit.UIImageView imgJeger {
			get {
				this.__mt_imgJeger = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgJeger")));
				return this.__mt_imgJeger;
			}
			set {
				this.__mt_imgJeger = value;
				this.SetNativeField("imgJeger", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgPosisjon")]
		private MonoTouch.UIKit.UIImageView imgPosisjon {
			get {
				this.__mt_imgPosisjon = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgPosisjon")));
				return this.__mt_imgPosisjon;
			}
			set {
				this.__mt_imgPosisjon = value;
				this.SetNativeField("imgPosisjon", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgSkudd")]
		private MonoTouch.UIKit.UIImageView imgSkudd {
			get {
				this.__mt_imgSkudd = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgSkudd")));
				return this.__mt_imgSkudd;
			}
			set {
				this.__mt_imgSkudd = value;
				this.SetNativeField("imgSkudd", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgNotater")]
		private MonoTouch.UIKit.UIImageView imgNotater {
			get {
				this.__mt_imgNotater = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgNotater")));
				return this.__mt_imgNotater;
			}
			set {
				this.__mt_imgNotater = value;
				this.SetNativeField("imgNotater", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imgBilde")]
		private MonoTouch.UIKit.UIImageView imgBilde {
			get {
				this.__mt_imgBilde = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imgBilde")));
				return this.__mt_imgBilde;
			}
			set {
				this.__mt_imgBilde = value;
				this.SetNativeField("imgBilde", value);
			}
		}
	}
}
