// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ArtScreen")]
	public partial class ArtScreen {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextView __mt_txtDescription;
		
		private MonoTouch.UIKit.UILabel __mt_lblTitle;
		
		private MonoTouch.UIKit.UIImageView __mt_imageView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtDescription")]
		private MonoTouch.UIKit.UITextView txtDescription {
			get {
				this.__mt_txtDescription = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("txtDescription")));
				return this.__mt_txtDescription;
			}
			set {
				this.__mt_txtDescription = value;
				this.SetNativeField("txtDescription", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblTitle")]
		private MonoTouch.UIKit.UILabel lblTitle {
			get {
				this.__mt_lblTitle = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lblTitle")));
				return this.__mt_lblTitle;
			}
			set {
				this.__mt_lblTitle = value;
				this.SetNativeField("lblTitle", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageView")]
		private MonoTouch.UIKit.UIImageView imageView {
			get {
				this.__mt_imageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageView")));
				return this.__mt_imageView;
			}
			set {
				this.__mt_imageView = value;
				this.SetNativeField("imageView", value);
			}
		}
	}
}
