// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("StatsLoggMap")]
	public partial class StatsLoggMap {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.MapKit.MKMapView __mt_mapView;
		
		private MonoTouch.UIKit.UISegmentedControl __mt_mapTypeControl;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btPageCurl;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_btRefresh;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mapView")]
		private MonoTouch.MapKit.MKMapView mapView {
			get {
				this.__mt_mapView = ((MonoTouch.MapKit.MKMapView)(this.GetNativeField("mapView")));
				return this.__mt_mapView;
			}
			set {
				this.__mt_mapView = value;
				this.SetNativeField("mapView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mapTypeControl")]
		private MonoTouch.UIKit.UISegmentedControl mapTypeControl {
			get {
				this.__mt_mapTypeControl = ((MonoTouch.UIKit.UISegmentedControl)(this.GetNativeField("mapTypeControl")));
				return this.__mt_mapTypeControl;
			}
			set {
				this.__mt_mapTypeControl = value;
				this.SetNativeField("mapTypeControl", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btPageCurl")]
		private MonoTouch.UIKit.UIBarButtonItem btPageCurl {
			get {
				this.__mt_btPageCurl = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btPageCurl")));
				return this.__mt_btPageCurl;
			}
			set {
				this.__mt_btPageCurl = value;
				this.SetNativeField("btPageCurl", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btRefresh")]
		private MonoTouch.UIKit.UIBarButtonItem btRefresh {
			get {
				this.__mt_btRefresh = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("btRefresh")));
				return this.__mt_btRefresh;
			}
			set {
				this.__mt_btRefresh = value;
				this.SetNativeField("btRefresh", value);
			}
		}
	}
}
