// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("StatsHitrate")]
	public partial class StatsHitrate {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIImageView __mt_imageView;
		
		private MonoTouch.UIKit.UIPickerView __mt_pickerView;
		
		private MonoTouch.UIKit.UILabel __mt_label1;
		
		private MonoTouch.UIKit.UILabel __mt_label2;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("imageView")]
		private MonoTouch.UIKit.UIImageView imageView {
			get {
				this.__mt_imageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageView")));
				return this.__mt_imageView;
			}
			set {
				this.__mt_imageView = value;
				this.SetNativeField("imageView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("pickerView")]
		private MonoTouch.UIKit.UIPickerView pickerView {
			get {
				this.__mt_pickerView = ((MonoTouch.UIKit.UIPickerView)(this.GetNativeField("pickerView")));
				return this.__mt_pickerView;
			}
			set {
				this.__mt_pickerView = value;
				this.SetNativeField("pickerView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("label1")]
		private MonoTouch.UIKit.UILabel label1 {
			get {
				this.__mt_label1 = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("label1")));
				return this.__mt_label1;
			}
			set {
				this.__mt_label1 = value;
				this.SetNativeField("label1", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("label2")]
		private MonoTouch.UIKit.UILabel label2 {
			get {
				this.__mt_label2 = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("label2")));
				return this.__mt_label2;
			}
			set {
				this.__mt_label2 = value;
				this.SetNativeField("label2", value);
			}
		}
	}
}
