// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("StatsGenericWebView")]
	public partial class StatsGenericWebView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIWebView __mt_webView;
		
		private MonoTouch.UIKit.UITextView __mt_lblFooter;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("webView")]
		private MonoTouch.UIKit.UIWebView webView {
			get {
				this.__mt_webView = ((MonoTouch.UIKit.UIWebView)(this.GetNativeField("webView")));
				return this.__mt_webView;
			}
			set {
				this.__mt_webView = value;
				this.SetNativeField("webView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lblFooter")]
		private MonoTouch.UIKit.UITextView lblFooter {
			get {
				this.__mt_lblFooter = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("lblFooter")));
				return this.__mt_lblFooter;
			}
			set {
				this.__mt_lblFooter = value;
				this.SetNativeField("lblFooter", value);
			}
		}
	}
}
