// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JaktLogg {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("StatsBesteJegere")]
	public partial class StatsBesteJegere {
		
		private MonoTouch.UIKit.UITableView __mt_view;
		
		private MonoTouch.UIKit.UISegmentedControl __mt_segmentedControl;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UITableView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("segmentedControl")]
		private MonoTouch.UIKit.UISegmentedControl segmentedControl {
			get {
				this.__mt_segmentedControl = ((MonoTouch.UIKit.UISegmentedControl)(this.GetNativeField("segmentedControl")));
				return this.__mt_segmentedControl;
			}
			set {
				this.__mt_segmentedControl = value;
				this.SetNativeField("segmentedControl", value);
			}
		}
	}
}
